#! /usr/bin/perl

use File::Basename;
use File::Copy;
use Data::Dumper;

my %packages;

if (not defined $ARGV[0]) {
    print "smartrpmsort directory [subdirectory name]\n";
    print "\n";
    print "Keep only newest RPM package version in provided directory and\n";
    print "move older ones to subdirectory\n";
    exit 0;
}

my $dir = $ARGV[0];
my $archive_fn = defined $ARGV[1] ? $ARGV[1] : "archive";
my $archive_dir = $dir . "/" . $archive_fn;
my $ok = 1;

for my $path (glob "$dir/*.rpm") {
    my $fn = basename $path;
    $fn =~ m:^(.+?)-([0-9\.]+)-([0-9]+)\.(el\d+_\d+|el\d+|)[^-]*:;
    my $name = $1;
    my $version = $2;
    my $release = $3;
    my $rhel = $4;
    if ($version =~ m/^(\d+)\.(\d+)\.(\d+)$/) {
        my $sort_key = sprintf("%05d%05d%05d%05d-%s", $1, $2, $3, $release, $rhel);
        #print "'$fn' name='$name' ('$1','$2','$3','$release','$rhel') -> sort_key='$sort_key'\n";
        $packages{$name}{$sort_key} = $fn;
    } else {
        print "Failed to parse version string '$version' for '$fn'\n";
    }
}

#print Dumper(\%packages);

for my $name (sort keys %packages) {
    my $versions_ref = $packages{$name};
    my %versions = %$versions_ref;
    my @keys = reverse sort keys %versions;
    print "\n";
    print "LEAVE $versions{$keys[0]} where it is\n";
    for (my $i = 1; $i <= $#keys; $i++) {
        if ( ! -d $archive_dir ) {
            mkdir($archive_dir) or die "Failed to create directory $archive_dir: $!";
        }
        my $fn = basename $versions{$keys[$i]};
        my $src = "$dir/$fn";
        my $dest = "$archive_dir/$fn";
        print "    MOVE: $src => $dest: ";
        if (move("$src", "$dest")) {
            print "OK\n";
        } else {
            print "$!\n";
            $ok = 0;
        }
    }
}

exit $ok ? 0 : 1;
