#! /usr/bin/perl

#
#  Checks out required revision from GIT (current directory) into tempory directory
#  and builds RPM packages from it.
#
#  Examples:
#
#  ./smartbuildrev
#       package top in current directory, use currently checked out revision
#
#  ./smartbuildrev FOO
#       package top in current directory, use revision FOO (for example tag FOO)
#
#  ./smartbuildrev FOO BAR
#       package top in directory BAR, use revision FOO (for example tag FOO)
#
use strict;
use File::Temp qw/tempdir/;

my $rev = "HEAD";
my $top_opt = "";
if ($#ARGV == 0) {
    $rev = $ARGV[0];
} elsif ($#ARGV == 1) {
    $top_opt = "-C $ARGV[1]"
} else {
   die "No more than one argument expected";
}

my $build_top = tempdir(CLEANUP => 1);
my $build_dir = "$build_top/$rev";

print("Build directory: $build_dir\n");

my $cmd = "git $top_opt archive --format=tar --prefix=$rev/ --output $build_top/__source__.tar $rev:";
print "Running: $cmd\n";
system($cmd) == 0 or die "Failed to run $cmd: $!";

$cmd = "tar xf $build_top/__source__.tar -C $build_top";
print "Running: $cmd\n";
system($cmd) == 0 or die "Failed to run $cmd: $!";

unlink("$build_top/__source__.tar");

$cmd = "make -C $build_dir rpm";
print "Running: $cmd\n";
system($cmd) == 0 or die "Failed to build RPM package for revision $rev";
